[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "robot_acoustic_gui"
version = "0.1.0"
description = "Application de contrôle du robot acoustique et acquisition."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

# Liste des dépendances de votre projet
dependencies = [
    "pyserial",
    "pygame",
    "configparser",
    "PySide6",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-mock",
]

[tool.setuptools.packages.find]
where = ["src"]