[PulseSettings]
# Chemin complet vers votre projet PULSE .pls
# Utiliser des doubles anti-slashs (\\) ou des slashs (/) pour la compatibilité
project_path = C:\\Users\\riaublanc\\PycharmProjects\\robot-acoustic-gui\\src\\labshop_interface\\pulse_projects\\MinimalTest.pls

# Répertoire où les fichiers de mesure ASCII seront sauvegardés
save_path_dir = C:\\Users\\riaublanc\\PycharmProjects\\robot-acoustic-gui\\src\\labshop_interface\\mesures_pulse_ascii

# Nom du FunctionGroup dans Pulse qui contient les fonctions à sauvegarder
function_group_to_save = ASauver

# Répertoire pour les fichiers de log du driver
log_dir = C:\\Users\\riaublanc\\PycharmProjects\\robot-acoustic-gui\\src\\labshop_interface\\logs_pulse_driver