[RATIOS]
# Steps par unité physique (mm ou degré)
# Notez les signes négatifs pour Y et Phi
X = 542.873
Y = -539.153
Z = 360.120
THETA = 227.544
PHI = -69.958

[OFFSETS]
# Décalages cinématiques en mm pour le calcul de la position de la capsule
CORRECTION_THETA_X = 48.0
CORRECTION_THETA_Y = 37.0
CORRECTION_THETA_Z = 0.0
CORRECTION_PHI_L = 53.0