[SERIAL]
port = COM7
baudrate = 9600
timeout = 0.5

[ROBOT_SPEEDS]
# Vitesses pour le contrôle manuel en unité/seconde (mm/s ou deg/s)
jog_xy_mm_s = 92
jog_z_mm_s = 55
jog_rot_deg_s = 65

# Paramètres pour les mouvements profilés (déplacements vers une cible)
# Unités en steps/s^2. Elles sont envoyées directement au driver Galil.
accel_steps_s2 = 100000
decel_steps_s2 = 100000

[RATIOS]
# Steps par unité physique (mm ou degré)
# Notez les signes négatifs pour Y et Phi
x = 542.873
y = -539.153
z = 360.120
theta = 227.544
phi = -69.958

[OFFSETS]
# Décalages cinématiques en mm pour le calcul de la position de la capsule
correction_theta_x = 48.0
correction_theta_y = 37.0
correction_theta_z = 0.0
correction_phi_l = 53.0